### ISSUE TITLE
[0.2.0] Syntax errors when creating repo

### ISSUE THREAD

**Issue by systemovich** [whiteinge/ok.sh#10]
On Kubuntu 14.04, when I try to create a repo, I get these errors:

    $ octokit.sh create_repo testing_octokit
    /home/user/bin/octokit.sh: 397: local: |: bad variable name
    /home/user/bin/octokit.sh: 577: /home/user/bin/octokit.sh: [[: not found

I guess it is because the shebang is `#!/usr/bin/env sh` and `sh` does not support `local` or `[[`.

When I run it with `bash`, I get another error:

    $ bash octokit.sh create_repo testing_octokit
    Client Error: 422 Unprocessable Entity

**Comment by whiteinge** [comment]
Yikes. How did that sneak in there? Thanks for filing the issue! I pushed a quick hotfix: https://github.com/whiteinge/ok.sh/releases/tag/0.2.1

The `local` statements are ok. Although it's not specified by POSIX all current bourne implementations respect it.

I'll file an issue to get integration tests added for this.

**Comment by whiteinge** [comment]
Closing. Please reopen if you encounter additional trouble.
