### ISSUE TITLE
Add meta data

### ISSUE THREAD

**Issue by szepeviktor** [whiteinge/ok.sh#37]
Please add meta data to ok.sh.
For example
```bash
#!/bin/bash
#
# One line description for this script.
#
# VERSION       :semver
# DATE          :2017-12-31
# URL           :https://github.com/szepeviktor/debian-server-tools
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# BASH-VERSION  :4.2+
# DEPENDS       :apt-get install package
# REFS          :url
# DOCS          :url
# SOURCE        :url
# UPSTREAM      :url
# LOCATION      :/usr/local/sbin/script.sh
# OWNER         :root:root
# PERMISSION    :0755
# SYMLINK       :/usr/local/sbin/alias.sh
# CRON-HOURLY   :/usr/local/sbin/script.sh
# CRON-DAILY    :/usr/local/sbin/script.sh
# CRON-WEEKLY   :/usr/local/sbin/script.sh
# CRON-MONTHLY  :/usr/local/sbin/script.sh | mailx -E -s "subject" root
# CRON.D        :2 2<-->* * *<->root<-->/usr/local/sbin/script.sh
# CONFIG        :~/.config/script/configuration
```

**Comment by whiteinge** [comment]
I'm not familiar with this. What is it for?

**Comment by szepeviktor** [comment]
I've happened to open ok.sh on my server a couple of days ago and only googling for "A GitHub API client library written in POSIX sh" revealed what it is for.

You must know several languages and systems - for example PHP docblock - where meta headers are useful to understand the code.

It has no meaning to a machine although I use it to install my shell scripts
https://github.com/szepeviktor/debian-server-tools/blob/master/install.sh#L21-L40

**Comment by szepeviktor** [comment]
I don't mean to use *all* of them!

**Comment by whiteinge** [comment]
Thanks for the examples. I'll get some added.
