### ISSUE TITLE
Tag name that looks like a float not treated as string

### ISSUE THREAD

**Issue by folknor** [whiteinge/ok.sh#47]
So I try to use create_release with these arguments: `stellaris-mods testing 5.20170918 body="* Test\n * Test2"`

And I get this result:
```
0000: {.  "message": "Invalid request.\n\nFor 'properties/tag_name', 5
0040: .20170918 is not a string.",.  "documentation_url": "https://dev
0080: eloper.github.com/v3".}.
```

Sent data:
```
=> Send data, 109 bytes (0x6d)
0000: {"tag_name": 5.20170918, "body": "* Updated readme.md with chang
0040: es from steam.bbcode.\n* Skogfisk eplepai."}.
== Info: upload completely sent off: 109 out of 109 bytes
```

I get the same result if I quote the argument on the command line, like:
`stellaris-mods testing '5.20170918' body="* Test\n * Test2"`

I have not tried using " to quote it, and I don't have time to do so right now (because I deleted the repository already and I need to go make dinner).

**Comment by whiteinge** [comment]
Thanks for the report! I've added support for quotes in #49. Just make sure to escape them otherwise the shell will consume them before the script is invoked.
