### ISSUE TITLE
Create tag as part of release?

### ISSUE THREAD

**Issue by atrauzzi** [whiteinge/ok.sh#55]
Github's releases UI allows you to create new tags as part of creating a new release.  Could this functionality also be exposed via the `create_release` command?

**Comment by whiteinge** [comment]
That is the default behavior for that [API call](https://developer.github.com/v3/repos/releases/#create-a-release). I gave `create_release` a quick test and it created a new tag in my test repo. Make sure the access token you're using has push access to the repo you're working with.

**Comment by atrauzzi** [comment]
Ahh, I just realized, I need to pass the `target_commitish`.  My bad :)
