### ISSUE TITLE
Fix Busybox compatibility (or come up with another way to make a POSIX-like env)

### ISSUE THREAD

**Issue by whiteinge** [whiteinge/ok.sh#68]
I used to test this against Busybox installed to a local directory, sandboxed via `env -i`. I know Busybox isn't exactly POSIX but it's pretty close, and keep the POSIX docs nearby when you're wondering about a particular flag or command. Anyway I can't think of a better way to get a near-POSIX environment set up. (Suggestions very welcome if someone has an idea here.)

It's been a while since I've done that and a few non-compatible things have snuck in. Busybox doesn't seem to have `pr` (even though it's POSIX), and there's a syntax error (unclosed `}`) somewhere in the file that Busybox's `sh` is choking on that `dash` is otherwise fine with.

So, either:
- Come up with a different way to make a POSIX env for testing and remove mention of Busybox from the README;
- or, Fix Busybox compatibility.

**Comment by dubiouscript** [comment]
>or, Fix Busybox compatibility.

this appears to work for me 
`nix-shell -p busybox --command "busybox sh -x ./ok.sh-0.3.0/ok.sh [...ect] "` 
( BusyBox v1.29.3 from nixpkgs-unstable )

`nix-shell --pure -p curl -p coreutils  -p busybox  --command " ./ok.sh-0.3.0/ok.sh [...ect] "`

 in my case [...ect] = list_issues  $repo
