### ISSUE TITLE
Flesh out a few more common functions

### ISSUE THREAD

**Issue by whiteinge** [whiteinge/ok.sh#7]
Create issues, create milestones, make a pull request, etc.

**Comment by laughedelic** [comment]
Any updates here?

**Comment by whiteinge** [comment]
@laughedelic [creating a milestone was added](https://github.com/whiteinge/ok.sh#create_milestone) semi-recently. You're very welcome to dive in here. [Creating these functions is straightforward](https://github.com/whiteinge/ok.sh/blob/b296137/ok.sh#L1355-L1389). 😄

**Comment by whiteinge** [comment]
Closing since the functions mentioned in OP have been added. There's plenty more endpoints to add of course but I don't think we need an issue to track them.
