### ISSUE TITLE
no way to create_issue?

### ISSUE THREAD

**Issue by nickdesaulniers** [whiteinge/ok.sh#73]
From reading the docs and source to ok.sh, I didn't see any way to create an issue?  I'm looking to file an issue for every warning in my code; I think I would be able to do so with that.

**Comment by whiteinge** [comment]
Looks like no one has gotten around to adding it yet. They're usually easy to add, however it would be useful if we had a quick way to create arrays too since a few of the issue fields use those. I'll get that added shortly.

**Comment by whiteinge** [comment]
Added array support and a create_issue function. Let me know if you run into any issues. Thanks for raising the question.

**Comment by nickdesaulniers** [comment]
will give it a shot, thank you!
