### ISSUE TITLE
what is a direction querystring argument?

### ISSUE THREAD

**Issue by andersfylling** [whiteinge/ok.sh#87]
I'm struggling to find information about this. What values can I inject?

Edit: I assume it's ordering. But it should be clarified in the docs if that is the case.

**Comment by whiteinge** [comment]
That is a common parameter that GitHub uses across many of their endpoints such as in the list issues docs. Values can be `asc` or `desc`. More information here:

https://developer.github.com/v3/issues/#parameters

**Comment by whiteinge** [comment]
Feel free to reopen if there any remaining questions.
